name = "lead-capture"
main = "lead-capture/src/index.ts"
compatibility_date = "2025-10-08"

[[d1_databases]]
binding = "OPS_DB"
database_name = "nour-ops"
database_id = "89262bb6-8a4d-4f70-93a9-106b7c2bb8b7"

[[d1_databases]]
binding = "DB"
database_name = "nour-leads"
database_id = "82edcad3-020e-46a3-99b6-0148ec5c65e2"
